apiVersion: batch/v1
kind: Job
metadata:
  name: kmb-dummy-pipeline-job-1
  labels:
    jobgroup: intelkmb-demo
spec:
  template:
    metadata:
      labels:
        jobgroup: intelkmb-demo
        vpu.intel.com/vpu-usage: low
        vpu.intel.com/codec-usage: medium
    spec:
      restartPolicy: Never
      containers:
        -
          name: ubuntu-full
          image: ubuntu:20.04
          securityContext:
            capabilities:
              add: ["SYS_RAWIO"]
          command: [ "/bin/bash", "/data/launch_gst_dummy.sh"]
          resources:
            limits:
              kmb.intel.com/vpu: 1
              kmb.intel.com/codec: 1
