apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: devplugin
  labels:
    app: devplugin
spec:
  selector:
    matchLabels:
      name: devplugin
  template:
    metadata:
      labels:
        name: devplugin
    spec:
      initContainers:
      - name: await
        image: busybox
        command:
        - sh
        - -c
        - |
          while [ ! -S /tmp/hddlunite_service.sock ]; do
            echo waiting for hddlunite_service.sock
            sleep 5s
          done
          echo created
        volumeMounts:
        - mountPath: /tmp
          name: socket
      containers:
      - name: devplugin
        image: gar-registry.caas.intel.com/virtiot/hddl_dev_plugin:1.1
        securityContext:
          privileged: true
        command: [ "/hddl_plugin"]
        volumeMounts:
        - mountPath: /dev/xlnk
          name: xlnk
        - mountPath: /dev/dri/card0
          name: dri
        - mountPath: /tmp
          name: socket
        - mountPath: /var/lib/kubelet/device-plugins
          name: kubelet
      volumes:
      - name: socket
        hostPath:
          path: /tmp
      - name: xlnk
        hostPath:
          path: /dev/xlnk
      - name: dri
        hostPath:
          path: /dev/dri/card0
      - name: kubelet
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory
