apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hddl
  labels:
    app: hddl
spec:
  selector:
    matchLabels:
      name: hddl
  template:
    metadata:
      labels:
        name: hddl
    spec:
      containers:
      - name: hddl
        image: $HDDL_IMAGE_NAME:$HDDL_IMAGE_TAG
        securityContext:
          privileged: true
        command: ["sh", "-c", "rm -rf /var/tmp/mode_set ; /run_hddl_service.sh"]
        volumeMounts:
        - mountPath: /dev/xlnk
          name: xlnk
        - mountPath: /var/tmp
          name: socket
        - mountPath: /opt/intel/vpu_accelerator_samples/hddlunite/config/hddl_service.config
          name: hddlserviceconfig
          subPath: hddl_service.config
      volumes:
      - name: socket
        hostPath:
          path: /var/tmp
      - name: xlnk
        hostPath:
          path: /dev/xlnk
      - name: hddlserviceconfig
        configMap:
          name: hddlserviceconfig
