apiVersion: batch/v1
kind: Job
metadata:
  name: fullpipe-$RANDOM_STR-01
  labels:
    jobgroup: fullpipe
spec:
  template:
    metadata:
      labels:
        jobgroup: fullpipe
    spec:
      restartPolicy: Never
      containers:
      - name: fullpipe
        image: $HDDL_IMAGE_NAME:$HDDL_IMAGE_TAG
        command: [ "$HDDL_TEST_FILE"]
        env:
        - name: TEST_NAME
          value: "TEST_01"
        - name: HVA_TEST_TIMEOUT
          value: "30"
        resources:
          limits:
            kmb.intel.com/device: $HDDL_KMB_COUNT

