apiVersion: batch/v1
kind: Job
metadata:
  name: kmb-full-pipeline-job-2
  labels:
    jobgroup: intelkmb-demo
spec:
  template:
    metadata:
      labels:
        jobgroup: intelkmb-demo
        vpu.intel.com/vpu-usage: low
        vpu.intel.com/codec-usage: medium
    spec:
      restartPolicy: Never
      containers:
        -
          name: kmb-full
          image: gar-registry.caas.intel.com/virtiot/kmb_full:20201215-0817
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_RAWIO"]
          command: [ "/bin/bash", "/data/launch_gst_full.sh"]
          resources:
            limits:
              kmb.intel.com/vpu: 1
              kmb.intel.com/codec: 1
          volumeMounts:
          - name: kmb-vol
            mountPath: /data
      volumes:
        - name: kmb-vol
          hostPath:
            path: /data
            type: Directory

