apiVersion: batch/v1
kind: Job
metadata:
  name: fullpipekpi
  labels:
    jobgroup: fullpipe
spec:
  template:
    metadata:
      labels:
        jobgroup: fullpipe
    spec:
      restartPolicy: Never
      containers:
      - name: fullpipe
        image: gar-registry.caas.intel.com/virtiot/hddlunite_connect:20200908-2044
        command: [ "/run_kpi.sh"]
        resources:
          limits:
            edgeai.intel.com/kmb: 3

