apiVersion: batch/v1
kind: Job
metadata:
  name: fullpipe
  labels:
    jobgroup: fullpipe
spec:
  template:
    metadata:
      labels:
        jobgroup: fullpipe
    spec:
      restartPolicy: Never
      containers:
      - name: fullpipe
        image: gar-registry.caas.intel.com/virtiot/hddlunite_connect:20200908-2044
        command: [ "/run_test.sh"]
        env:
        - name: TEST_NAME
          value: "TEST_01"
        - name: HVA_TEST_TIMEOUT
          value: "30"
        resources:
          limits:
            kmb.intel.com/device: 3

